name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install npm dependencies
        run: |
          npm ci --no-audit
          npm ci --no-audit --prefix cordova-plugin-moodleapp

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Android APK
        run: npx ionic cordova build android --prod --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: moodle-app-apk
          path: platforms/android/app/build/outputs/apk/release/*.aab
